name: woofood
description: woofood_mobile

version: 2.4.1
code: 7

environment:
  sdk: ">=2.2.2 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 0.1.2
  google_maps_flutter: 0.5.30
  google_map_location_picker: 3.3.3
  mvc_pattern: 6.3.0
  global_configuration: 1.5.0
  http: 0.12.2
  html: 0.14.0+3
  shared_preferences: 0.5.10
  flutter_html: 1.0.2
  flutter_svg: 0.18.1
  location: 3.0.2
  flutter_inappbrowser: 2.0.2
  url_launcher: 5.5.0
  firebase_messaging: 7.0.0
  cached_network_image: 2.2.0+1
  fluttertoast: 4.0.1
  flutter_staggered_grid_view: 0.3.2
  intl_utils: 1.6.3
  carousel_slider: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/img/
    
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
flutter_intl:
  enabled: true
